version: "3.7"

services:
  site:
    image: dtekcth/serve-repo
    build: .
    environment:
      GIT_REPO: https://github.com/dtekcth/Serve-Repo.git
      LOCATION_CFG: autoindex on;
    ports:
      - "8080:80"
    volumes:
      - ./runner.sh:/runner.sh
      - ./template.conf:/template.conf
